### ISSUE TITLE
Object #<Object> has no method 'execSync'

### ISSUE THREAD

**Issue by sawant** [typicode/user-startup#6]
This error occured when trying to install and run hotel for the first time. Didn't post in hotel because it seems like a user-startup module error:

`hotel start`

```
/usr/local/lib/node_modules/hotel/node_modules/user-startup/lib/startup/darwin.js:34
  cp.execSync('launchctl load ' + file);
     ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.create (/usr/local/lib/node_modules/hotel/node_modules/user-startup/lib/startup/darwin.js:34:6)
    at Object.start (/usr/local/lib/node_modules/hotel/lib/cli/daemon.js:22:11)
    at module.exports (/usr/local/lib/node_modules/hotel/lib/cli/index.js:32:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hotel/bin/index.js:2:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

npm version: 1.4.21
node version: 0.10.30

**Comment by sawant** [comment]
Upon investigation, it seems like a hotel issue as it's using an old version of user-startup module.
